AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 29
    Runtime: nodejs12.x
    Environment:
      Variables:
        TABLE_NAME: !Ref NotesTable

Resources:
  ###################################
  # Catalog microservice
  ###################################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'dev'

  CreateNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'Create-Notes'
      CodeUri: backend/catalog/create-notes
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: '/note'
            Method: POST

  FetchNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'Fetch-Notes'
      CodeUri: backend/catalog/fetch-notes
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: '/note'
            Method: GET

  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'Notes'
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'hashKey'
          AttributeType: 'S'
        # - AttributeName: 'sortKey'
        #   AttributeType: 'S'
      KeySchema:
        - AttributeName: 'hashKey'
          KeyType: 'HASH'
        # - AttributeName: 'sortKey'
        #   KeyType: 'RANGE'
